# Generated by Django 4.1.2 on 2022-10-22 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "mobile_num",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1000000000),
                            django.core.validators.MaxValueValidator(9999999999),
                        ]
                    ),
                ),
                ("company_name", models.CharField(max_length=100, unique=True)),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("DISTRIBUTOR", "Distributor"),
                            ("PRODUCTION", "Production"),
                            ("STORE", "Store"),
                        ],
                        default="DISTRIBUTOR",
                        max_length=15,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GROCERIES", "Groceries"),
                            ("ELECTRONICS", "Electronics"),
                            ("STATIONERY", "Stationery"),
                            ("FURNITURE", "Furniture"),
                            ("CONSTRUCTION", "Construction"),
                        ],
                        default="GROCERIES",
                        max_length=15,
                    ),
                ),
                (
                    "budget",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(2000)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
